# -*- coding: utf-8 -*-
"""KMeansClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7blykU9b6qjp0yIgB9Q7lqB5-MvPI3L
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans

# 1. DATA PREPARATION
# Load the class dataset
car_data = pd.read_csv('AllCars.csv')

# Cleaning: Remove non-ordinal 'Make' and filter for valid car styles
official_styles = ['Sedan', 'SUV', 'Van', 'Pickup', 'Jeep']
car_data = car_data[car_data['Style'].isin(official_styles)]

# Filtering: Remove entries with unrealistic interior volumes (noise)
car_data = car_data[car_data['Volume'] > 50]

# Normalization: Scale Volume and Doors to a 0-1 range for equal weighting
feature_scaler = MinMaxScaler()
car_data[['Volume', 'Doors']] = feature_scaler.fit_transform(car_data[['Volume', 'Doors']])

#2. K-MEANS CLUSTERING
# Initialize K-Means to find exactly 5 clusters
kmeans_model = KMeans(n_clusters=5, random_state=42, n_init=10)
car_data['ClusterID'] = kmeans_model.fit_predict(car_data[['Volume', 'Doors']])

# 3. CLUSTER LABELING & ACCURACY CALCULATION
cluster_label_map = {}
accuracy_results = []

for cluster_id in range(5):
    # Extract data points belonging to the current cluster
    cluster_subset = car_data[car_data['ClusterID'] == cluster_id]
    cluster_size = len(cluster_subset)

    # Identify the majority car style within this cluster
    majority_style = cluster_subset['Style'].mode()[0]
    cluster_label_map[cluster_id] = majority_style

    # Calculate accuracy: (cars matching majority style) / (total cars in cluster)
    correct_matches = len(cluster_subset[cluster_subset['Style'] == majority_style])
    cluster_accuracy = correct_matches / cluster_size

    # Store metrics for ClusterAccuracy.csv
    accuracy_results.append({
        'ClusterStyle': majority_style,
        'SizeOfCluster': cluster_size,
        'Accuracy': cluster_accuracy
    })

# Assign the predicted style to each car based on its cluster
car_data['ClusterStyle'] = car_data['ClusterID'].map(cluster_label_map)

# 4. EXPORTING RESULTS
# File 1: Full list of cars with their assigned Cluster Style
car_data[['Volume', 'Doors', 'Style', 'ClusterStyle']].to_csv('ClusterCars.csv', index=False)

# File 2: Metrics for each of the 5 clusters
pd.DataFrame(accuracy_results).to_csv('ClusterAccuracy.csv', index=False)

print("K-Means Processing Complete.")